name: airsim-drone-control
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    # Core dependencies
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - airsim==1.8.1
    - pydantic==2.5.0
    - python-multipart==0.0.6
    - websockets==12.0
    - aiofiles==23.2.1
    - pyyaml==6.0.1
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    
    # Development tools
    - black==23.11.0
    - isort==5.12.0
    - pytest==7.4.3
    - pytest-asyncio==0.21.1
    - pytest-cov==4.1.0
    
    # Future AI capabilities (commented out for now)
    # - numpy>=1.24.0
    # - pandas>=2.0.0
    # - scikit-learn>=1.3.0
    # - torch>=2.0.0
    # - transformers>=4.30.0
    # - opencv-python>=4.8.0 